version: "3"

services:
  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: always
    networks:
      - cdbs_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localdontuseglobal
      MONGO_INITDB_DATABASE: cdbs_v1
    ports:
      - 27017:27017

  git-importer:
    build:
      context: apps/git-import/
    container_name: git-importer
    networks:
      - cdbs_net
    command: python -u app.py

  sonarqube:
    image: sonarqube:8-community
    container_name: sonarqube
    restart: always
    networks:
      - cdbs_net
    ports:
      - 9000:9000

  gradle-runner:
    build:
      context: apps/gradle-runner/
      dockerfile: openjdk8.dockerfile
    networks:
      - cdbs_net

networks:
  cdbs_net:
