version: "3"

services:
  mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localdontuseglobal
      MONGO_INITDB_DATABASE: cdbs_v1
    ports:
      - 27017:27017
